In [1]:
import pandas as pd

In [2]:
results_er = pd.read_csv("results/param_sweeps/sweep_trials_er.csv")
results_ws = pd.read_csv("results/param_sweeps/sweep_trials_ws.csv")
results_ba = pd.read_csv("results/param_sweeps/sweep_trials_ba.csv")

In [3]:
for name, results in [("ER", results_er), ("WS", results_ws), ("BA", results_ba)]:
    print(f"Results {name}:")
    print("Total number of trials:", len(results))
    
    sorted_results = results.sort_values(by="best_score", ascending=False)
    display(sorted_results.head(10))  # change/remove head(10) to show more

Results ER:
Total number of trials: 3125

,crossover_proportion,crossover_edges,mutation_prob,elitism_proportion,repeat,seed,best_score,elapsed_sec,error
1329,0.4,1,0.8,0.3,4,20673,-110701.489512,81.302897,NaN
1330,0.4,1,0.9,0.2,2,16981,-111655.619857,76.932094,NaN
656,0.3,1,0.8,0.1,2,21447,-111783.159511,71.609848,NaN
928,0.3,2,1.0,0.4,2,16356,-111790.384740,79.489254,NaN
534,0.2,5,0.6,0.1,1,15642,-111824.210632,76.764204,NaN
719,0.3,1,1.0,0.2,0,17735,-111862.064801,75.083422,NaN
539,0.2,5,0.7,0.4,2,18631,-111998.530387,72.675182,NaN
1166,0.3,5,0.7,0.2,3,17346,-112015.360623,73.842132,NaN
367,0.2,3,1.0,0.4,2,18256,-112194.086128,76.321046,NaN
2019,0.5,1,1.0,0.1,0,13237,-112238.648017,76.384064,NaN

Results WS:
Total number of trials: 3125

,crossover_proportion,crossover_edges,mutation_prob,elitism_proportion,repeat,seed,best_score,elapsed_sec,error
471,0.2,4,0.8,0.1,2,16791,-71225.517994,63.050625,NaN
243,0.2,2,1.0,0.1,2,14939,-71253.535239,59.521314,NaN
188,0.2,1,1.0,0.1,2,18440,-71306.374801,78.239215,NaN
1404,0.4,1,1.0,0.3,4,18308,-71341.206341,61.080766,NaN
748,0.3,1,1.0,0.1,4,20700,-71400.543437,61.900872,NaN
880,0.3,2,1.0,0.1,2,22028,-71441.069308,60.632390,NaN
241,0.2,2,1.0,0.2,1,21977,-71555.238231,59.091812,NaN
1455,0.4,2,0.8,0.1,0,19908,-71562.335345,58.249067,NaN
628,0.2,5,1.0,0.1,0,18158,-71588.085835,61.139495,NaN
903,0.3,2,1.0,0.3,4,13100,-71604.107462,60.681474,NaN

Results BA:
Total number of trials: 3125

,crossover_proportion,crossover_edges,mutation_prob,elitism_proportion,repeat,seed,best_score,elapsed_sec,error
365,0.2,3,1.0,0.2,2,16966,-57990.564156,64.179842,NaN
282,0.2,3,0.9,0.3,3,15238,-58132.208416,58.933366,NaN
624,0.2,5,1.0,0.2,4,21864,-58230.172175,63.458740,NaN
330,0.2,3,1.0,0.2,1,16965,-58236.596158,61.172951,NaN
499,0.2,4,1.0,0.4,4,19329,-58240.431205,62.747128,NaN
956,0.3,3,0.9,0.2,0,12376,-58344.915641,63.604592,NaN
456,0.2,4,0.9,0.1,2,13835,-58398.943274,62.892024,NaN
461,0.2,4,0.7,0.2,3,20433,-58516.014075,66.238569,NaN
1847,0.4,5,0.9,0.1,4,21793,-58562.857329,62.428737,NaN
1315,0.4,1,0.8,0.1,4,16901,-58571.133030,61.912072,NaN

In [4]:
results_agg_er = pd.read_csv("results/param_sweeps/sweep_agg_er.csv")
results_agg_ws = pd.read_csv("results/param_sweeps/sweep_agg_ws.csv")
results_agg_ba = pd.read_csv("results/param_sweeps/sweep_agg_ba.csv")

In [5]:
display(results_agg_er.head(10))

,crossover_proportion,crossover_edges,mutation_prob,elitism_proportion,mean,std,count
0,0.3,1,1.0,0.1,-113997.562069,1446.664058,5
1,0.2,2,1.0,0.1,-114737.375738,834.432997,5
2,0.2,3,1.0,0.2,-115010.472520,2375.041073,5
3,0.3,1,1.0,0.2,-115064.748529,2537.735801,5
4,0.3,4,1.0,0.2,-115064.836664,1889.362722,5
5,0.3,1,0.9,0.1,-115324.627443,1700.614630,5
6,0.3,3,1.0,0.1,-115673.600299,1567.512619,5
7,0.2,5,0.9,0.1,-115831.010095,2527.493562,5
8,0.2,2,0.9,0.1,-116075.169591,2286.540900,5
9,0.3,2,0.8,0.1,-116095.723699,1885.920701,5

In [6]:
display(results_agg_ws.head(10))

,crossover_proportion,crossover_edges,mutation_prob,elitism_proportion,mean,std,count
0,0.2,2,1.0,0.2,-71746.124063,148.394587,5
1,0.3,2,0.9,0.1,-72649.624745,973.317672,5
2,0.2,5,1.0,0.1,-72893.834967,1844.149437,5
3,0.3,2,1.0,0.1,-72898.073097,1184.473254,5
4,0.2,1,1.0,0.1,-73101.514502,1563.691837,5
5,0.2,3,1.0,0.2,-73349.105943,1507.855077,5
6,0.3,1,1.0,0.1,-73417.795181,2742.851873,5
7,0.3,5,1.0,0.1,-73569.028870,1484.809062,5
8,0.2,4,1.0,0.2,-73723.704039,1458.820005,5
9,0.4,1,1.0,0.3,-73737.852752,2281.094228,5

In [7]:
display(results_agg_ba.head(10))

,crossover_proportion,crossover_edges,mutation_prob,elitism_proportion,mean,std,count
0,0.2,3,1.0,0.2,-60285.580862,2090.941073,5
1,0.2,3,0.8,0.2,-60411.204303,1073.510560,5
2,0.4,3,1.0,0.3,-60668.938670,2063.302033,5
3,0.4,5,1.0,0.1,-60687.435176,1393.422151,5
4,0.2,1,1.0,0.1,-60707.730731,412.592835,5
5,0.3,1,1.0,0.1,-60776.841999,866.600855,5
6,0.4,3,1.0,0.1,-60812.396572,1395.294649,5
7,0.5,1,1.0,0.1,-60827.339419,1100.383677,5
8,0.2,3,0.9,0.3,-60846.642740,1810.483849,5
9,0.2,1,0.9,0.2,-60847.368970,970.836505,5