In [ ]:
import os
from tqdm import tqdm
import sys
if not hasattr(sys.modules[__name__], "cwd_changed"):
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__name__))))
    sys.modules[__name__].cwd_changed = True

import warnings 
warnings.filterwarnings("ignore")
import logging
logging.getLogger('pgmpy').setLevel(logging.WARNING)


import pandas as pd
from utils.graph import dag_to_cpdag
from metrics.graph import compare_dags
from utils.results import *

## 1.1: Grid (Sample Size x P_noise) (Noisy Logic Gates)

In [ ]:
import pickle

subset = '1.1'
# subset = 'toyMedium'

def load_results(subset):
    global results_by_label

    # with open(f'results/pc/{subset}.pkl', 'rb') as f:
    #     results_pc = pickle.load(f)
    # with open(f'results/ges/{subset}.pkl', 'rb') as f:
    #     results_ges = pickle.load(f)
    with open(f'results/hc/{subset}.pkl', 'rb') as f:
        results_hc = pickle.load(f)

    with open(f'old_results/results/hc/{subset}.pkl', 'rb') as f:
        results_hc_old = pickle.load(f)

    # with open(f'results/ea_ues/{subset}.pkl', 'rb') as f:
    #     results_ea_ues = pickle.load(f)
    # with open(f'results/ea_ies/{subset}.pkl', 'rb') as f:
    #     results_ea_ies = pickle.load(f)
    # with open(f'results/ea_fes/{subset}.pkl', 'rb') as f:
    #     results_ea_fes = pickle.load(f)

    # with open(f'results/ea_upu/{subset}.pkl', 'rb') as f:
    #     results_ea_upu = pickle.load(f)
    # with open(f'results/ea_ipu/{subset}.pkl', 'rb') as f:
    #     results_ea_ipu = pickle.load(f)
    
    # with open(f'results/ea_final_greedy/{subset}.pkl', 'rb') as f:
    #     results_ea_final_greedy = pickle.load(f)

    # with open(f'results/ea_final_greedy_f/{subset}.pkl', 'rb') as f:
    #     results_ea_final_greedy_f = pickle.load(f)

    results_by_label = {
        # "PC": results_pc,
        # "GES": results_ges,
        "HC": results_hc,
        "HC Old": results_hc_old,
        # "EA Final Greedy": results_ea_final_greedy,
        # "EA Final 2 gens": results_ea_final_greedy_f,
        # "EA Uninformed": results_ea_ues,
        # "EA Informed": results_ea_ies,
        # "EA Fully Informed": results_ea_fes,
        # "EA Uninformed (PU)": results_ea_upu,
        # "EA Informed (PU)": results_ea_ipu,
    }
    
load_results(subset)
mapping="experiments/RQ1/1.1/grid_mapping.csv"
x_col="samples"
y_col="p_noise"

### Metrics Comparison

In [ ]:
import ipywidgets as widgets
from IPython.display import display, clear_output
import matplotlib.pyplot as plt

# --- UI ---
metric_dropdown = widgets.Dropdown(
    options=["Recall (Collider)", "F1 (Collider)", "SHD", "Recall (Synergy)"],
    value="Recall (Collider)",
    description="Metric:",
)

out = widgets.Output()

def render(metric: str):
    """Render the heatmap for the selected metric."""
    with out:
        clear_output(wait=True)

        # Important: close prior figures to avoid stacking / memory leaks
        plt.close("all")

        fig, axes = plot_final_heatmap(
            results_by_label,
            mapping=mapping,
            subset_metrics=[metric],
            plot_metric=metric,
            x_col=x_col,
            y_col=y_col,
        )

        # Ensure the latest figure is shown in the output area
        plt.show()

def on_metric_change(change):
    if change["name"] == "value":
        render(change["new"])

metric_dropdown.observe(on_metric_change, names="value")

# Display UI + initial render
display(widgets.VBox([metric_dropdown, out]))
render(metric_dropdown.value)

VBox(children=(Dropdown(description='Metric:', options=('Recall (Collider)', 'F1 (Collider)', 'SHD', 'Recall (…

## 1.2: Grid (Num Roots x Num Synergistic Nodes)) (Noisy Logic Gates)

In [ ]:
import pickle

subset = '1.2'
# subset = 'toyMedium'
load_results(subset)
mapping = "experiments/RQ1/1.2/grid_mapping.csv"
x_col="n_roots"
y_col="n_syn"

### Metrics

In [ ]:
import ipywidgets as widgets
from IPython.display import display, clear_output
import matplotlib.pyplot as plt

# --- UI ---
metric_dropdown = widgets.Dropdown(
    options=["Recall (Collider)", "F1 (Collider)", "SHD", "Recall (Synergy)"],
    value="Recall (Collider)",
    description="Metric:",
)

out = widgets.Output()

def render(metric: str):
    """Render the heatmap for the selected metric."""
    with out:
        clear_output(wait=True)

        # Important: close prior figures to avoid stacking / memory leaks
        plt.close("all")

        fig, axes = plot_final_heatmap(
            results_by_label,
            mapping=mapping,
            subset_metrics=[metric],
            plot_metric=metric,
            x_col=x_col,
            y_col=y_col,
        )

        # Ensure the latest figure is shown in the output area
        plt.show()

def on_metric_change(change):
    if change["name"] == "value":
        render(change["new"])

metric_dropdown.observe(on_metric_change, names="value")

# Display UI + initial render
display(widgets.VBox([metric_dropdown, out]))
render(metric_dropdown.value)

VBox(children=(Dropdown(description='Metric:', options=('Recall (Collider)', 'F1 (Collider)', 'SHD', 'Recall (…

## 1.3: Varying MI/WMS-Synergy (JointPMF)

In [ ]:
import pickle

subset = 'jpmf_grid'
# subset = 'toyMedium'

load_results(subset)
mapping="experiments/RQ1/jpmf_grid/grid_mapping.csv"

x_col="target_mi"
y_col="syn_cutoff"

In [ ]:
### Metrics and Algorithms

In [ ]:
# --- UI ---
metric_dropdown = widgets.Dropdown(
    options=["Recall (Collider)", "F1 (Collider)", "SHD", "Recall (Synergy)"],
    value="Recall (Collider)",
    description="Metric:",
)

out = widgets.Output()

def render(metric: str):
    """Render the heatmap for the selected metric."""
    with out:
        clear_output(wait=True)

        # Important: close prior figures to avoid stacking / memory leaks
        plt.close("all")

        fig, axes = plot_final_heatmap(
            results_by_label,
            mapping=mapping,
            subset_metrics=[metric],
            plot_metric=metric,
            x_col=x_col,
            y_col=y_col,
        )

        # Ensure the latest figure is shown in the output area
        plt.show()

def on_metric_change(change):
    if change["name"] == "value":
        render(change["new"])

metric_dropdown.observe(on_metric_change, names="value")

# Display UI + initial render
display(widgets.VBox([metric_dropdown, out]))
render(metric_dropdown.value)

VBox(children=(Dropdown(description='Metric:', options=('Recall (Collider)', 'F1 (Collider)', 'SHD', 'Recall (…

In [2]:
hillclimber[hillclimber["logic"] == "OR" ].describe()

,run_id,n_inputs,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score,True Positives (undirected),False Positives (undirected),False Negatives (undirected),SHD (undirected),Precision (undirected),Recall (undirected),F1 Score (undirected)
count,4.000000,4.0,4.0,4.000000,4.0,4.000000,4.000000,4.00,4.000000,4.0,4.00,4.0,4.00,4.00000,4.0,4.00
mean,6.000000,10.0,1.5,1.250000,0.5,1.750000,0.583500,0.75,0.650000,2.0,0.75,0.0,0.75,0.75025,1.0,0.85
std,8.164966,0.0,1.0,1.258306,1.0,2.217356,0.419479,0.50,0.443471,0.0,0.50,0.0,0.50,0.16650,0.0,0.10
min,0.000000,10.0,0.0,0.000000,0.0,0.000000,0.000000,0.00,0.000000,2.0,0.00,0.0,0.00,0.66700,1.0,0.80
25%,1.500000,10.0,1.5,0.750000,0.0,0.750000,0.500250,0.75,0.600000,2.0,0.75,0.0,0.75,0.66700,1.0,0.80
50%,3.000000,10.0,2.0,1.000000,0.0,1.000000,0.667000,1.00,0.800000,2.0,1.00,0.0,1.00,0.66700,1.0,0.80
75%,7.500000,10.0,2.0,1.500000,0.5,2.000000,0.750250,1.00,0.850000,2.0,1.00,0.0,1.00,0.75025,1.0,0.85
max,18.000000,10.0,2.0,3.000000,2.0,5.000000,1.000000,1.00,1.000000,2.0,1.00,0.0,1.00,1.00000,1.0,1.00

In [5]:
hillclimber[hillclimber["logic"] == "AND" ].describe()

,run_id,n_inputs,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score,True Positives (undirected),False Positives (undirected),False Negatives (undirected),SHD (undirected),Precision (undirected),Recall (undirected),F1 Score (undirected)
count,8.000000,8.0,8.000000,8.000000,8.000000,8.00000,8.000000,8.000000,8.000000,8.0,8.000000,8.0,8.000000,8.000000,8.0,8.000000
mean,9.875000,10.0,1.250000,1.250000,0.750000,2.00000,0.625000,0.625000,0.625000,2.0,0.500000,0.0,0.500000,0.854250,1.0,0.908375
std,5.303301,0.0,1.035098,1.752549,1.035098,2.77746,0.517549,0.517549,0.517549,0.0,0.755929,0.0,0.755929,0.207651,0.0,0.132949
min,1.000000,10.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,2.0,0.000000,0.0,0.000000,0.500000,1.0,0.667000
25%,6.750000,10.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,2.0,0.000000,0.0,0.000000,0.667000,1.0,0.800000
50%,9.500000,10.0,2.000000,0.000000,0.000000,0.00000,1.000000,1.000000,1.000000,2.0,0.000000,0.0,0.000000,1.000000,1.0,1.000000
75%,14.250000,10.0,2.000000,3.000000,2.000000,5.00000,1.000000,1.000000,1.000000,2.0,1.000000,0.0,1.000000,1.000000,1.0,1.000000
max,17.000000,10.0,2.000000,4.000000,2.000000,6.00000,1.000000,1.000000,1.000000,2.0,2.000000,0.0,2.000000,1.000000,1.0,1.000000

In [6]:
hillclimber[hillclimber["logic"] == "XOR" ].describe()

,run_id,n_inputs,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score,True Positives (undirected),False Positives (undirected),False Negatives (undirected),SHD (undirected),Precision (undirected),Recall (undirected),F1 Score (undirected)
count,8.000000,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
mean,10.875000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
std,5.383507,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,3.000000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
25%,7.250000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
50%,11.500000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
75%,13.750000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
max,19.000000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0

Peter-Clarkson

In [7]:
pc_summary = pd.read_csv("results/pc/pc_summary.csv")

In [8]:
pc_summary[pc_summary["logic"] == "OR"].describe()

,run_id,n_inputs,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score,True Positives (undirected),False Positives (undirected),False Negatives (undirected),SHD (undirected),Precision (undirected),Recall (undirected),F1 Score (undirected)
count,8.000000,8.0,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.0,8.000000,8.000000,8.0,8.000000
mean,6.250000,10.0,1.875000,2.125000,0.125000,2.250000,0.468750,0.937500,0.625250,2.125000,1.875000,0.0,1.875000,0.531250,1.0,0.690750
std,5.257647,0.0,0.353553,0.353553,0.353553,0.707107,0.088388,0.176777,0.118087,0.353553,0.353553,0.0,0.353553,0.088388,0.0,0.067175
min,0.000000,10.0,1.000000,2.000000,0.000000,2.000000,0.250000,0.500000,0.333000,2.000000,1.000000,0.0,1.000000,0.500000,1.0,0.667000
25%,1.750000,10.0,2.000000,2.000000,0.000000,2.000000,0.500000,1.000000,0.667000,2.000000,2.000000,0.0,2.000000,0.500000,1.0,0.667000
50%,6.000000,10.0,2.000000,2.000000,0.000000,2.000000,0.500000,1.000000,0.667000,2.000000,2.000000,0.0,2.000000,0.500000,1.0,0.667000
75%,9.750000,10.0,2.000000,2.000000,0.000000,2.000000,0.500000,1.000000,0.667000,2.000000,2.000000,0.0,2.000000,0.500000,1.0,0.667000
max,14.000000,10.0,2.000000,3.000000,1.000000,4.000000,0.500000,1.000000,0.667000,3.000000,2.000000,0.0,2.000000,0.750000,1.0,0.857000

In [9]:
pc_summary[pc_summary["logic"] == "XOR" ].describe()

,run_id,n_inputs,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score,True Positives (undirected),False Positives (undirected),False Negatives (undirected),SHD (undirected),Precision (undirected),Recall (undirected),F1 Score (undirected)
count,8.000000,8.0,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.00000,8.000000,8.000000,8.000000
mean,9.500000,10.0,0.625000,2.500000,1.375000,3.875000,0.156250,0.312500,0.208375,0.750000,2.375000,1.375000,3.75000,0.187500,0.333375,0.238125
std,4.898979,0.0,0.916125,0.755929,0.916125,1.356203,0.229031,0.458063,0.305499,1.035098,0.744024,0.916125,1.38873,0.258775,0.471438,0.329976
min,3.000000,10.0,0.000000,2.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,2.00000,0.000000,0.000000,0.000000
25%,5.750000,10.0,0.000000,2.000000,0.750000,3.500000,0.000000,0.000000,0.000000,0.000000,2.000000,0.750000,2.75000,0.000000,0.000000,0.000000
50%,9.000000,10.0,0.000000,2.000000,2.000000,4.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,4.00000,0.000000,0.000000,0.000000
75%,13.500000,10.0,1.250000,3.000000,2.000000,4.250000,0.312500,0.625000,0.416500,2.000000,2.250000,2.000000,4.25000,0.500000,0.750250,0.595000
max,16.000000,10.0,2.000000,4.000000,2.000000,6.000000,0.500000,1.000000,0.667000,2.000000,4.000000,2.000000,6.00000,0.500000,1.000000,0.667000

In [11]:
pc_summary[pc_summary["logic"] == "AND" ].describe()

,run_id,n_inputs,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score,True Positives (undirected),False Positives (undirected),False Negatives (undirected),SHD (undirected),Precision (undirected),Recall (undirected),F1 Score (undirected)
count,4.000000,4.0,4.00000,4.00000,4.00000,4.0,4.000000,4.000000,4.00000,4.00000,4.000000,4.0,4.000000,4.000,4.0,4.00000
mean,16.000000,10.0,1.50000,3.00000,0.50000,3.5,0.458500,0.750000,0.54175,2.50000,2.000000,0.0,2.000000,0.625,1.0,0.75025
std,4.082483,0.0,0.57735,2.44949,0.57735,3.0,0.393653,0.288675,0.36328,0.57735,1.414214,0.0,1.414214,0.250,0.0,0.16650
min,10.000000,10.0,1.00000,0.00000,0.00000,0.0,0.167000,0.500000,0.25000,2.00000,0.000000,0.0,0.000000,0.500,1.0,0.66700
25%,15.250000,10.0,1.00000,1.50000,0.00000,1.5,0.167000,0.500000,0.25000,2.00000,1.500000,0.0,1.500000,0.500,1.0,0.66700
50%,17.500000,10.0,1.50000,3.50000,0.50000,4.0,0.333500,0.750000,0.45850,2.50000,2.500000,0.0,2.500000,0.500,1.0,0.66700
75%,18.250000,10.0,2.00000,5.00000,1.00000,6.0,0.625000,1.000000,0.75025,3.00000,3.000000,0.0,3.000000,0.625,1.0,0.75025
max,19.000000,10.0,2.00000,5.00000,1.00000,6.0,1.000000,1.000000,1.00000,3.00000,3.000000,0.0,3.000000,1.000,1.0,1.00000

In [12]:
notears_summary = pd.read_csv("results/notears/notears_summary.csv")

In [13]:
notears_summary[notears_summary["logic"] == "OR"].describe()

,run_id,n_inputs,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score,True Positives (undirected),False Positives (undirected),False Negatives (undirected),SHD (undirected),Precision (undirected),Recall (undirected),F1 Score (undirected)
count,7.000000,7.0,7.0,7.000000,7.0,7.000000,7.0,7.0,7.0,7.000000,7.0,7.000000,7.000000,7.0,7.000000,7.000000
mean,5.857143,10.0,0.0,1.857143,2.0,3.857143,0.0,0.0,0.0,1.857143,0.0,0.142857,0.142857,1.0,0.928571,0.952429
std,5.080307,0.0,0.0,0.377964,0.0,0.377964,0.0,0.0,0.0,0.377964,0.0,0.377964,0.377964,0.0,0.188982,0.125862
min,1.000000,10.0,0.0,1.000000,2.0,3.000000,0.0,0.0,0.0,1.000000,0.0,0.000000,0.000000,1.0,0.500000,0.667000
25%,2.500000,10.0,0.0,2.000000,2.0,4.000000,0.0,0.0,0.0,2.000000,0.0,0.000000,0.000000,1.0,1.000000,1.000000
50%,5.000000,10.0,0.0,2.000000,2.0,4.000000,0.0,0.0,0.0,2.000000,0.0,0.000000,0.000000,1.0,1.000000,1.000000
75%,7.000000,10.0,0.0,2.000000,2.0,4.000000,0.0,0.0,0.0,2.000000,0.0,0.000000,0.000000,1.0,1.000000,1.000000
max,16.000000,10.0,0.0,2.000000,2.0,4.000000,0.0,0.0,0.0,2.000000,0.0,1.000000,1.000000,1.0,1.000000,1.000000

In [14]:
notears_summary[notears_summary["logic"] == "XOR"].describe()

,run_id,n_inputs,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score,True Positives (undirected),False Positives (undirected),False Negatives (undirected),SHD (undirected),Precision (undirected),Recall (undirected),F1 Score (undirected)
count,7.000000,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0
mean,12.000000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
std,4.760952,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,4.000000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
25%,10.000000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
50%,12.000000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
75%,15.000000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
max,18.000000,10.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0

In [15]:
notears_summary[notears_summary["logic"] == "AND"].describe()

,run_id,n_inputs,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score,True Positives (undirected),False Positives (undirected),False Negatives (undirected),SHD (undirected),Precision (undirected),Recall (undirected),F1 Score (undirected)
count,6.000000,6.0,6.0,6.000000,6.0,6.000000,6.0,6.0,6.0,6.0,6.000000,6.0,6.000000,6.000000,6.0,6.000000
mean,10.833333,10.0,0.0,2.166667,2.0,4.166667,0.0,0.0,0.0,2.0,0.166667,0.0,0.166667,0.944500,1.0,0.966667
std,6.735478,0.0,0.0,0.408248,0.0,0.408248,0.0,0.0,0.0,0.0,0.408248,0.0,0.408248,0.135947,0.0,0.081650
min,0.000000,10.0,0.0,2.000000,2.0,4.000000,0.0,0.0,0.0,2.0,0.000000,0.0,0.000000,0.667000,1.0,0.800000
25%,7.750000,10.0,0.0,2.000000,2.0,4.000000,0.0,0.0,0.0,2.0,0.000000,0.0,0.000000,1.000000,1.0,1.000000
50%,12.000000,10.0,0.0,2.000000,2.0,4.000000,0.0,0.0,0.0,2.0,0.000000,0.0,0.000000,1.000000,1.0,1.000000
75%,14.750000,10.0,0.0,2.000000,2.0,4.000000,0.0,0.0,0.0,2.0,0.000000,0.0,0.000000,1.000000,1.0,1.000000
max,19.000000,10.0,0.0,3.000000,2.0,5.000000,0.0,0.0,0.0,2.0,1.000000,0.0,1.000000,1.000000,1.0,1.000000