In [1]:
import os
import sys

if not hasattr(sys.modules[__name__], "cwd_changed"):
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__name__))))
    sys.modules[__name__].cwd_changed = True

from src.pipeline import Pipeline
from src.benchmark import run_ea
from src.experiments import generate_chain_no_synergy

In [2]:
configs = {
        # 'folder': 'data/precomputed_cpds/two_roots',
        "folder": 'data/BinaryDataSmallNoNoise',
        'algorithm': 'ea',
        'replications': 1,
        'max_generations': 1,
        'population_size': 5,
    }

pipeline = Pipeline(configs, run_ea)
pipeline.experiment_process(generate_chain_no_synergy)

{'True Positives': 1,
 'False Positives': 1,
 'False Negatives': 1,
 'SHD': 2,
 'Precision': 0.5,
 'Recall': 0.5,
 'F1 Score': 0.5}

In [3]:
pipeline.run()

Processing CSV files: 100%|██████████| 40/40 [00:02<00:00, 16.01it/s]
Processing Bnlearn datasets: 100%|██████████| 5/5 [00:01<00:00,  2.58it/s]

In [7]:
pipeline.experiment1_results[0]

,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score
Chain (No Synergy),1.0,1.0,1.0,2.0,0.500,0.500,0.500
Chain (With Synergy),3.0,2.0,0.0,2.0,0.600,1.000,0.750
Chain with D,1.0,1.0,1.0,2.0,0.500,0.500,0.500
Fork (Three Variables),0.0,2.0,2.0,4.0,0.000,0.000,0.000
Fork Synergy (Three Variables),0.0,2.0,2.0,4.0,0.000,0.000,0.000
Collider (Three Variables),2.0,0.0,1.0,1.0,1.000,0.667,0.800
Fork with D,0.0,3.0,2.0,5.0,0.000,0.000,0.000
Fork Synergy with D,0.0,2.0,2.0,4.0,0.000,0.000,0.000
Collider with D,0.0,2.0,3.0,5.0,0.000,0.000,0.000
Large Discrete,0.0,6.0,8.0,14.0,0.000,0.000,0.000
Multi-Parent Synergy (Three Parents),3.0,1.0,0.0,1.0,0.750,1.000,0.857
Multi-Parent Synergy (4 Parents),4.0,5.0,0.0,5.0,0.444,1.000,0.615
Multi-Parent Synergy (5 Parents),5.0,9.0,0.0,9.0,0.357,1.000,0.526
Mediator Synergy,3.0,2.0,0.0,2.0,0.600,1.000,0.750

In [5]:
pipeline.experiment2_results[0]

,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score
Asia,7.0,17.0,1.0,18.0,0.292,0.875,0.438
Cancer,2.0,7.0,2.0,9.0,0.222,0.500,0.308
Earthquake,2.0,2.0,2.0,4.0,0.500,0.500,0.500
Sachs,1.0,7.0,16.0,23.0,0.125,0.059,0.080
Survey,1.0,7.0,5.0,12.0,0.125,0.167,0.143

In [ ]:
pipeline.experiment2()

,True Positives,False Positives,False Negatives,SHD,Precision,Recall,F1 Score
Asia,7.0,20.0,1.0,21.0,0.259,0.875,0.400
Cancer,2.0,7.0,2.0,9.0,0.222,0.500,0.308
Earthquake,2.0,4.0,2.0,6.0,0.333,0.500,0.400
Sachs,0.0,9.0,17.0,26.0,0.000,0.000,0.000
Survey,4.0,8.0,2.0,10.0,0.333,0.667,0.444
Alarm,0.0,43.0,46.0,89.0,0.000,0.000,0.000
Barley,78.0,1046.0,6.0,1052.0,0.069,0.929,0.129
Child,0.0,19.0,25.0,44.0,0.000,0.000,0.000
Insurance,0.0,23.0,52.0,75.0,0.000,0.000,0.000
Mildew,19.0,572.0,27.0,599.0,0.032,0.413,0.060
Water,3.0,21.0,63.0,84.0,0.125,0.045,0.067

In [ ]:
# from src.experiments import load_bnlearn_data
# pipeline.experiment_process(load_bnlearn_data)  # Identity function

### Aggregated Results

In [2]:
import os

[i for i in os.listdir("results") if i.endswith(".pkl")]

['all_results_2025-08-27 15:01:43.393198.pkl',
 'all_results_20250827_150715.pkl',
 'experiment_1_results_2025-08-27 15:00:18.901745.pkl',
 'experiment_1_results_2025-08-27 15:01:43.392090.pkl',
 'experiment_1_results_20250827_150715.pkl',
 'experiment_2_results_2025-08-27 15:00:18.902701.pkl',
 'experiment_2_results_2025-08-27 15:01:43.392779.pkl',
 'experiment_2_results_20250827_150715.pkl']

In [8]:
from datetime import datetime
datetime.now().timestamp()

1756299866.238856

In [38]:
import pickle
all_results = pickle.load(open("results/all_results_20250827_150715.pkl", "rb"))
experiments_1 = pickle.load(open("results/experiment_1_results_20250827_150715.pkl", "rb"))
experiments_2 = pickle.load(open("results/experiment_2_results_20250827_150715.pkl", "rb"))

In [20]:
folders = list(all_results.keys())

In [35]:
# Aggregated results for the first folder
for each_folder in all_results.keys():
    print(f"Folder: {each_folder}")
    metrics = all_results[each_folder]
    mean_df = pd.concat(metrics.values()).groupby(level=0).agg(['mean', 'std'])
    mean_df.to_csv(f"results/aggregated_metrics_{each_folder.split('/')[-1]}.csv")

Folder: data/BinaryDataMedium20Noise
Folder: data/BinaryDataMedium50Noise

In [ ]:
import pandas as pd
metrics = all_results[folders[0]]
metrics.values()
# aggregated_metrics = pd.concat(metrics.values(), axis=1)
# mean_metrics = aggregated_metrics.mean(axis=1)
# std_metrics = aggregated_metrics.std(axis=1)
# mean_metrics

{0:                                          0             1             2   \
 True Positives                     1.000000      0.000000      0.000000
 False Positives                   19.000000     19.000000     15.000000
 False Negatives                   29.000000     30.000000     30.000000
 SHD                               48.000000     49.000000     45.000000
 Precision                          0.050000      0.000000      0.000000
 Recall                             0.033000      0.000000      0.000000
 F1 Score                           0.040000      0.000000      0.000000
 Precision (Collider)               0.000000      0.000000      0.000000
 Recall (Collider)                  0.000000      0.000000      0.000000
 F1 (Collider)                      0.000000      0.000000      0.000000
 Recall (Synergy Multi-Parent)      0.000000      0.000000      0.000000
 True Model BIC                -11207.023161 -11202.092544 -11205.066162
 BIC                           -13387.326251 -13177.954138 -13239.453908
 Triplets Found                     0.000000      0.000000      0.000000
 Missing Triplets                  15.000000     15.000000     15.000000
 Number of Inputs                  20.000000     20.000000     20.000000
 Number of Samples               1000.000000   1000.000000   1000.000000

                                          3             4             5   \
 True Positives                     1.000000      2.000000      1.000000
 False Positives                   21.000000     21.000000     15.000000
 False Negatives                   29.000000     28.000000     29.000000
 SHD                               50.000000     49.000000     44.000000
 Precision                          0.045000      0.087000      0.062000
 Recall                             0.033000      0.067000      0.033000
 F1 Score                           0.038000      0.075000      0.043000
 Precision (Collider)               0.000000      0.000000      0.000000
 Recall (Collider)                  0.000000      0.000000      0.000000
 F1 (Collider)                      0.000000      0.000000      0.000000
 Recall (Synergy Multi-Parent)      0.000000      0.000000      0.000000
 True Model BIC                -11211.678970 -11206.528873 -11207.186526
 BIC                           -13246.293402 -13638.977327 -13477.463867
 Triplets Found                     0.000000      0.000000      0.000000
 Missing Triplets                  15.000000     15.000000     15.000000
 Number of Inputs                  20.000000     20.000000     20.000000
 Number of Samples               1000.000000   1000.000000   1000.000000

                                          6             7             8   \
 True Positives                     2.000000      1.000000      4.000000
 False Positives                   15.000000     15.000000     14.000000
 False Negatives                   28.000000     29.000000     26.000000
 SHD                               43.000000     44.000000     40.000000
 Precision                          0.118000      0.062000      0.222000
 Recall                             0.067000      0.033000      0.133000
 F1 Score                           0.085000      0.043000      0.167000
 Precision (Collider)               0.000000      0.000000      0.000000
 Recall (Collider)                  0.000000      0.000000      0.000000
 F1 (Collider)                      0.000000      0.000000      0.000000
 Recall (Synergy Multi-Parent)      0.000000      0.000000      0.000000
 True Model BIC                -11209.212827 -11205.282414 -11210.878550
 BIC                           -13521.674925 -13400.391652 -13363.170894
 Triplets Found                     0.000000      0.000000      0.000000
 Missing Triplets                  15.000000     15.000000     15.000000
 Number of Inputs                  20.000000     20.000000     20.000000
 Number of Samples               1000.000000   1000.000000   1000.000000

                                          9   ...             30  \
 True Positives                     2.000000  ...       1.000000
 False Positives                   16.000000  ...      22.000000
 False Negatives                   28.000000  ...      29.000000
 SHD                               44.000000  ...      51.000000
 Precision                          0.111000  ...       0.043000
 Recall                             0.067000  ...       0.033000
 F1 Score                           0.083000  ...       0.038000
 Precision (Collider)               0.000000  ...       0.058824
 Recall (Collider)                  0.000000  ...       0.066667
 F1 (Collider)                      0.000000  ...       0.062500
 Recall (Synergy Multi-Parent)      0.000000  ...       0.066667
 True Model BIC                -11206.638490  ... -109763.378121
 BIC                           -13310.647377  ... -134147.079993
 Triplets Found                     0.000000  ...       1.000000
 Missing Triplets                  15.000000  ...      14.000000
 Number of Inputs                  20.000000  ...      20.000000
 Number of Samples               1000.000000  ...   10000.000000

                                           31             32             33  \
 True Positives                      1.000000       1.000000       0.000000
 False Positives                     8.000000      16.000000      19.000000
 False Negatives                    29.000000      29.000000      30.000000
 SHD                                37.000000      45.000000      49.000000
 Precision                           0.111000       0.059000       0.000000
 Recall                              0.033000       0.033000       0.000000
 F1 Score                            0.051000       0.043000       0.000000
 Precision (Collider)                0.000000       0.000000       0.000000
 Recall (Collider)                   0.000000       0.000000       0.000000
 F1 (Collider)                       0.000000       0.000000       0.000000
 Recall (Synergy Multi-Parent)       0.000000       0.000000       0.000000
 True Model BIC                -109758.105317 -109762.784089 -109765.457358
 BIC                           -134153.349558 -132799.516327 -132341.607839
 Triplets Found                      0.000000       0.000000       0.000000
 Missing Triplets                   15.000000      15.000000      15.000000
 Number of Inputs                   20.000000      20.000000      20.000000
 Number of Samples               10000.000000   10000.000000   10000.000000

                                           34             35             36  \
 True Positives                      4.000000       0.000000       2.000000
 False Positives                    15.000000      24.000000      20.000000
 False Negatives                    26.000000      30.000000      28.000000
 SHD                                41.000000      54.000000      48.000000
 Precision                           0.211000       0.000000       0.091000
 Recall                              0.133000       0.000000       0.067000
 F1 Score                            0.163000       0.000000       0.077000
 Precision (Collider)                0.100000       0.000000       0.000000
 Recall (Collider)                   0.066667       0.000000       0.000000
 F1 (Collider)                       0.080000       0.000000       0.000000
 Recall (Synergy Multi-Parent)       0.066667       0.000000       0.000000
 True Model BIC                -109755.512909 -109759.471120 -109763.992338
 BIC                           -132347.437653 -135058.129744 -133701.210207
 Triplets Found                      1.000000       0.000000       0.000000
 Missing Triplets                   14.000000      15.000000      15.000000
 Number of Inputs                   20.000000      20.000000      20.000000
 Number of Samples               10000.000000   10000.000000   10000.000000

                                           37             38             39
 True Positives                      2.000000       1.000000       2.000000
 False Positives                    19.000000      22.000000      18.000000
 False Negatives                    28.000000      29.000000      28.000000
 SHD                                47.000000      51.000000      46.000000
 Precision                           0.095000       0.043000       0.100000
 Recall                              0.067000       0.033000       0.067000
 F1 Score                            0.078000       0.038000       0.080000
 Precision (Collider)                0.000000       0.000000       0.000000
 Recall (Collider)                   0.000000       0.000000       0.000000
 F1 (Collider)                       0.000000       0.000000       0.000000
 Recall (Synergy Multi-Parent)       0.000000       0.000000       0.000000
 True Model BIC                -109753.500191 -109758.261855 -109758.446359
 BIC                           -132480.848836 -132452.475315 -132879.923146
 Triplets Found                      0.000000       0.000000       0.000000
 Missing Triplets                   15.000000      15.000000      15.000000
 Number of Inputs                   20.000000      20.000000      20.000000
 Number of Samples               10000.000000   10000.000000   10000.000000

 [17 rows x 40 columns],
 1:                                          0             1             2   \
 True Positives                     0.000000      2.000000      1.000000
 False Positives                   21.000000     23.000000      9.000000
 False Negatives                   30.000000     28.000000     29.000000
 SHD                               51.000000     51.000000     38.000000
 Precision                          0.000000      0.080000      0.100000
 Recall                             0.000000      0.067000      0.033000
 F1 Score                           0.000000      0.073000      0.050000
 Precision (Collider)               0.000000      0.000000      0.000000
 Recall (Collider)                  0.000000      0.000000      0.000000
 F1 (Collider)                      0.000000      0.000000      0.000000
 Recall (Synergy Multi-Parent)      0.000000      0.000000      0.000000
 True Model BIC                -11207.023161 -11202.092544 -11205.066162
 BIC                           -13341.630752 -13257.956115 -13214.105037
 Triplets Found                     0.000000      0.000000      0.000000
 Missing Triplets                  15.000000     15.000000     15.000000
 Number of Inputs                  20.000000     20.000000     20.000000
 Number of Samples               1000.000000   1000.000000   1000.000000

                                          3             4             5   \
 True Positives                     0.000000      3.000000      1.000000
 False Positives                   16.000000     19.000000     15.000000
 False Negatives                   30.000000     27.000000     29.000000
 SHD                               46.000000     46.000000     44.000000
 Precision                          0.000000      0.136000      0.062000
 Recall                             0.000000      0.100000      0.033000
 F1 Score                           0.000000      0.115000      0.043000
 Precision (Collider)               0.000000      0.000000      0.000000
 Recall (Collider)                  0.000000      0.000000      0.000000
 F1 (Collider)                      0.000000      0.000000      0.000000
 Recall (Synergy Multi-Parent)      0.000000      0.000000      0.000000
 True Model BIC                -11211.678970 -11206.528873 -11207.186526
 BIC                           -13379.664884 -13536.899299 -13431.616432
 Triplets Found                     0.000000      0.000000      0.000000
 Missing Triplets                  15.000000     15.000000     15.000000
 Number of Inputs                  20.000000     20.000000     20.000000
 Number of Samples               1000.000000   1000.000000   1000.000000

                                          6             7             8   \
 True Positives                     1.000000      0.000000      1.000000
 False Positives                   16.000000     23.000000     19.000000
 False Negatives                   29.000000     30.000000     29.000000
 SHD                               45.000000     53.000000     48.000000
 Precision                          0.059000      0.000000      0.050000
 Recall                             0.033000      0.000000      0.033000
 F1 Score                           0.043000      0.000000      0.040000
 Precision (Collider)               0.142857      0.000000      0.111111
 Recall (Collider)                  0.066667      0.000000      0.066667
 F1 (Collider)                      0.090909      0.000000      0.083333
 Recall (Synergy Multi-Parent)      0.066667      0.000000      0.066667
 True Model BIC                -11209.212827 -11205.282414 -11210.878550
 BIC                           -13464.482267 -13497.239862 -13382.727982
 Triplets Found                     1.000000      0.000000      1.000000
 Missing Triplets                  14.000000     15.000000     14.000000
 Number of Inputs                  20.000000     20.000000     20.000000
 Number of Samples               1000.000000   1000.000000   1000.000000

                                          9   ...             30  \
 True Positives                     1.000000  ...       1.000000
 False Positives                   15.000000  ...      16.000000
 False Negatives                   29.000000  ...      29.000000
 SHD                               44.000000  ...      45.000000
 Precision                          0.062000  ...       0.059000
 Recall                             0.033000  ...       0.033000
 F1 Score                           0.043000  ...       0.043000
 Precision (Collider)               0.125000  ...       0.000000
 Recall (Collider)                  0.066667  ...       0.000000
 F1 (Collider)                      0.086957  ...       0.000000
 Recall (Synergy Multi-Parent)      0.066667  ...       0.000000
 True Model BIC                -11206.638490  ... -109763.378121
 BIC                           -13236.712728  ... -134686.351829
 Triplets Found                     1.000000  ...       0.000000
 Missing Triplets                  14.000000  ...      15.000000
 Number of Inputs                  20.000000  ...      20.000000
 Number of Samples               1000.000000  ...   10000.000000

                                           31             32             33  \
 True Positives                      1.000000       0.000000       3.000000
 False Positives                    17.000000      17.000000      22.000000
 False Negatives                    29.000000      30.000000      27.000000
 SHD                                46.000000      47.000000      49.000000
 Precision                           0.056000       0.000000       0.120000
 Recall                              0.033000       0.000000       0.100000
 F1 Score                            0.042000       0.000000       0.109000
 Precision (Collider)                0.000000       0.000000       0.000000
 Recall (Collider)                   0.000000       0.000000       0.000000
 F1 (Collider)                       0.000000       0.000000       0.000000
 Recall (Synergy Multi-Parent)       0.000000       0.000000       0.000000
 True Model BIC                -109758.105317 -109762.784089 -109765.457358
 BIC                           -134098.739540 -132511.306345 -130723.025847
 Triplets Found                      0.000000       0.000000       0.000000
 Missing Triplets                   15.000000      15.000000      15.000000
 Number of Inputs                   20.000000      20.000000      20.000000
 Number of Samples               10000.000000   10000.000000   10000.000000

                                           34             35             36  \
 True Positives                      3.000000       3.000000       0.000000
 False Positives                    22.000000      21.000000      14.000000
 False Negatives                    27.000000      27.000000      30.000000
 SHD                                49.000000      48.000000      44.000000
 Precision                           0.120000       0.125000       0.000000
 Recall                              0.100000       0.100000       0.000000
 F1 Score                            0.109000       0.111000       0.000000
 Precision (Collider)                0.000000       0.000000       0.000000
 Recall (Collider)                   0.000000       0.000000       0.000000
 F1 (Collider)                       0.000000       0.000000       0.000000
 Recall (Synergy Multi-Parent)       0.000000       0.000000       0.000000
 True Model BIC                -109755.512909 -109759.471120 -109763.992338
 BIC                           -132945.381406 -133150.197824 -133971.470253
 Triplets Found                      0.000000       0.000000       0.000000
 Missing Triplets                   15.000000      15.000000      15.000000
 Number of Inputs                   20.000000      20.000000      20.000000
 Number of Samples               10000.000000   10000.000000   10000.000000

                                           37             38             39
 True Positives                      3.000000       4.000000       3.000000
 False Positives                    16.000000      15.000000      16.000000
 False Negatives                    27.000000      26.000000      27.000000
 SHD                                43.000000      41.000000      43.000000
 Precision                           0.158000       0.211000       0.158000
 Recall                              0.100000       0.133000       0.100000
 F1 Score                            0.122000       0.163000       0.122000
 Precision (Collider)                0.000000       0.000000       0.000000
 Recall (Collider)                   0.000000       0.000000       0.000000
 F1 (Collider)                       0.000000       0.000000       0.000000
 Recall (Synergy Multi-Parent)       0.000000       0.000000       0.000000
 True Model BIC                -109753.500191 -109758.261855 -109758.446359
 BIC                           -131143.035193 -132367.034685 -131720.365342
 Triplets Found                      0.000000       0.000000       0.000000
 Missing Triplets                   15.000000      15.000000      15.000000
 Number of Inputs                   20.000000      20.000000      20.000000
 Number of Samples               10000.000000   10000.000000   10000.000000

 [17 rows x 40 columns]}

In [25]:
mean_df = pd.concat(metrics.values(), axis=0).groupby(level=0).mean()
mean_df

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
BIC,-13364.478501,-13217.955127,-13226.779473,-13312.979143,-13587.938313,-13454.540149,-13493.078596,-13448.815757,-13372.949438,-13273.680052,...,-134416.715911,-134126.044549,-132655.411336,-131532.316843,-132646.409529,-134104.163784,-133836.340230,-131811.942014,-132409.755000,-132300.144244
F1 (Collider),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.045455,0.000000,0.041667,0.043478,...,0.031250,0.000000,0.000000,0.000000,0.040000,0.000000,0.000000,0.000000,0.000000,0.000000
F1 Score,0.020000,0.036500,0.025000,0.019000,0.095000,0.043000,0.064000,0.021500,0.103500,0.063000,...,0.040500,0.046500,0.021500,0.054500,0.136000,0.055500,0.038500,0.100000,0.100500,0.101000
False Negatives,29.500000,29.000000,29.500000,29.500000,27.500000,29.000000,28.500000,29.500000,27.500000,28.500000,...,29.000000,29.000000,29.500000,28.500000,26.500000,28.500000,29.000000,27.500000,27.500000,27.500000
False Positives,20.000000,21.000000,12.000000,18.500000,20.000000,15.000000,15.500000,19.000000,16.500000,15.500000,...,19.000000,12.500000,16.500000,20.500000,18.500000,22.500000,17.000000,17.500000,18.500000,17.000000
Missing Triplets,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,14.500000,15.000000,14.500000,14.500000,...,14.500000,15.000000,15.000000,15.000000,14.500000,15.000000,15.000000,15.000000,15.000000,15.000000
Number of Inputs,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,...,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
Number of Samples,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
Precision,0.025000,0.040000,0.050000,0.022500,0.111500,0.062000,0.088500,0.031000,0.136000,0.086500,...,0.051000,0.083500,0.029500,0.060000,0.165500,0.062500,0.045500,0.126500,0.127000,0.129000
Precision (Collider),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.071429,0.000000,0.055556,0.062500,...,0.029412,0.000000,0.000000,0.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000
Recall,0.016500,0.033500,0.016500,0.016500,0.083500,0.033000,0.050000,0.016500,0.083000,0.050000,...,0.033000,0.033000,0.016500,0.050000,0.116500,0.050000,0.033500,0.083500,0.083000,0.083500
Recall (Collider),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,0.033333,0.033333,...,0.033333,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,0.000000
Recall (Synergy Multi-Parent),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.033333,0.000000,0.033333,0.033333,...,0.033333,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,0.000000
SHD,49.500000,50.000000,41.500000,48.000000,47.500000,44.000000,44.000000,48.500000,44.000000,44.000000,...,48.000000,41.500000,46.000000,49.000000,45.000000,51.000000,46.000000,45.000000,46.000000,44.500000
Triplets Found,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.500000,0.500000,...,0.500000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000
True Model BIC,-11207.023161,-11202.092544,-11205.066162,-11211.678970,-11206.528873,-11207.186526,-11209.212827,-11205.282414,-11210.878550,-11206.638490,...,-109763.378121,-109758.105317,-109762.784089,-109765.457358,-109755.512909,-109759.471120,-109763.992338,-109753.500191,-109758.261855,-109758.446359
True Positives,0.500000,1.000000,0.500000,0.500000,2.500000,1.000000,1.500000,0.500000,2.500000,1.500000,...,1.000000,1.000000,0.500000,1.500000,3.500000,1.500000,1.000000,2.500000,2.500000,2.500000

In [29]:
mean_df = pd.concat(metrics.values()).groupby(level=0).agg(['mean', 'std'])
mean_df

                                         0                        1   \
                                       mean        std          mean
BIC                           -13364.478501  32.311597 -13217.955127
F1 (Collider)                      0.000000   0.000000      0.000000
F1 Score                           0.020000   0.028284      0.036500
False Negatives                   29.500000   0.707107     29.000000
False Positives                   20.000000   1.414214     21.000000
Missing Triplets                  15.000000   0.000000     15.000000
Number of Inputs                  20.000000   0.000000     20.000000
Number of Samples               1000.000000   0.000000   1000.000000
Precision                          0.025000   0.035355      0.040000
Precision (Collider)               0.000000   0.000000      0.000000
Recall                             0.016500   0.023335      0.033500
Recall (Collider)                  0.000000   0.000000      0.000000
Recall (Synergy Multi-Parent)      0.000000   0.000000      0.000000
SHD                               49.500000   2.121320     50.000000
Triplets Found                     0.000000   0.000000      0.000000
True Model BIC                -11207.023161   0.000000 -11202.092544
True Positives                     0.500000   0.707107      1.000000

                                                    2              \
                                     std          mean        std
BIC                            56.569941 -13226.779473  17.924359
F1 (Collider)                   0.000000      0.000000   0.000000
F1 Score                        0.051619      0.025000   0.035355
False Negatives                 1.414214     29.500000   0.707107
False Positives                 2.828427     12.000000   4.242641
Missing Triplets                0.000000     15.000000   0.000000
Number of Inputs                0.000000     20.000000   0.000000
Number of Samples               0.000000   1000.000000   0.000000
Precision                       0.056569      0.050000   0.070711
Precision (Collider)            0.000000      0.000000   0.000000
Recall                          0.047376      0.016500   0.023335
Recall (Collider)               0.000000      0.000000   0.000000
Recall (Synergy Multi-Parent)   0.000000      0.000000   0.000000
SHD                             1.414214     41.500000   4.949747
Triplets Found                  0.000000      0.000000   0.000000
True Model BIC                  0.000000 -11205.066162   0.000000
True Positives                  1.414214      0.500000   0.707107

                                         3                        4   \
                                       mean        std          mean
BIC                           -13312.979143  94.307879 -13587.938313
F1 (Collider)                      0.000000   0.000000      0.000000
F1 Score                           0.019000   0.026870      0.095000
False Negatives                   29.500000   0.707107     27.500000
False Positives                   18.500000   3.535534     20.000000
Missing Triplets                  15.000000   0.000000     15.000000
Number of Inputs                  20.000000   0.000000     20.000000
Number of Samples               1000.000000   0.000000   1000.000000
Precision                          0.022500   0.031820      0.111500
Precision (Collider)               0.000000   0.000000      0.000000
Recall                             0.016500   0.023335      0.083500
Recall (Collider)                  0.000000   0.000000      0.000000
Recall (Synergy Multi-Parent)      0.000000   0.000000      0.000000
SHD                               48.000000   2.828427     47.500000
Triplets Found                     0.000000   0.000000      0.000000
True Model BIC                -11211.678970   0.000000 -11206.528873
True Positives                     0.500000   0.707107      2.500000

                                          ...             35               \
                                     std  ...           mean          std
BIC                            72.180066  ... -134104.163784  1349.111598
F1 (Collider)                   0.000000  ...       0.000000     0.000000
F1 Score                        0.028284  ...       0.055500     0.078489
False Negatives                 0.707107  ...      28.500000     2.121320
False Positives                 1.414214  ...      22.500000     2.121320
Missing Triplets                0.000000  ...      15.000000     0.000000
Number of Inputs                0.000000  ...      20.000000     0.000000
Number of Samples               0.000000  ...   10000.000000     0.000000
Precision                       0.034648  ...       0.062500     0.088388
Precision (Collider)            0.000000  ...       0.000000     0.000000
Recall                          0.023335  ...       0.050000     0.070711
Recall (Collider)               0.000000  ...       0.000000     0.000000
Recall (Synergy Multi-Parent)   0.000000  ...       0.000000     0.000000
SHD                             2.121320  ...      51.000000     4.242641
Triplets Found                  0.000000  ...       0.000000     0.000000
True Model BIC                  0.000000  ... -109759.471120     0.000000
True Positives                  0.707107  ...       1.500000     2.121320

                                          36                         37  \
                                        mean         std           mean
BIC                           -133836.340230  191.102711 -131811.942014
F1 (Collider)                       0.000000    0.000000       0.000000
F1 Score                            0.038500    0.054447       0.100000
False Negatives                    29.000000    1.414214      27.500000
False Positives                    17.000000    4.242641      17.500000
Missing Triplets                   15.000000    0.000000      15.000000
Number of Inputs                   20.000000    0.000000      20.000000
Number of Samples               10000.000000    0.000000   10000.000000
Precision                           0.045500    0.064347       0.126500
Precision (Collider)                0.000000    0.000000       0.000000
Recall                              0.033500    0.047376       0.083500
Recall (Collider)                   0.000000    0.000000       0.000000
Recall (Synergy Multi-Parent)       0.000000    0.000000       0.000000
SHD                                46.000000    2.828427      45.000000
Triplets Found                      0.000000    0.000000       0.000000
True Model BIC                -109763.992338    0.000000 -109753.500191
True Positives                      1.000000    1.414214       2.500000

                                                      38             \
                                      std           mean        std
BIC                            945.977099 -132409.755000  60.415649
F1 (Collider)                    0.000000       0.000000   0.000000
F1 Score                         0.031113       0.100500   0.088388
False Negatives                  0.707107      27.500000   2.121320
False Positives                  2.121320      18.500000   4.949747
Missing Triplets                 0.000000      15.000000   0.000000
Number of Inputs                 0.000000      20.000000   0.000000
Number of Samples                0.000000   10000.000000   0.000000
Precision                        0.044548       0.127000   0.118794
Precision (Collider)             0.000000       0.000000   0.000000
Recall                           0.023335       0.083000   0.070711
Recall (Collider)                0.000000       0.000000   0.000000
Recall (Synergy Multi-Parent)    0.000000       0.000000   0.000000
SHD                              2.828427      46.000000   7.071068
Triplets Found                   0.000000       0.000000   0.000000
True Model BIC                   0.000000 -109758.261855   0.000000
True Positives                   0.707107       2.500000   2.121320

                                          39
                                        mean         std
BIC                           -132300.144244  819.931186
F1 (Collider)                       0.000000    0.000000
F1 Score                            0.101000    0.029698
False Negatives                    27.500000    0.707107
False Positives                    17.000000    1.414214
Missing Triplets                   15.000000    0.000000
Number of Inputs                   20.000000    0.000000
Number of Samples               10000.000000    0.000000
Precision                           0.129000    0.041012
Precision (Collider)                0.000000    0.000000
Recall                              0.083500    0.023335
Recall (Collider)                   0.000000    0.000000
Recall (Synergy Multi-Parent)       0.000000    0.000000
SHD                                44.500000    2.121320
Triplets Found                      0.000000    0.000000
True Model BIC                -109758.446359    0.000000
True Positives                      2.500000    0.707107

[17 rows x 80 columns]

In [30]:
mean_df.mean(axis=1)

BIC                             -31482.784173
F1 (Collider)                        0.015963
F1 Score                             0.049927
False Negatives                     14.669531
False Positives                     10.025013
Missing Triplets                     7.518566
Number of Inputs                    10.000000
Number of Samples                 2375.000000
Precision                            0.065783
Precision (Collider)                 0.021789
Recall                               0.041054
Recall (Collider)                    0.012904
Recall (Synergy Multi-Parent)        0.012904
SHD                                 24.305635
Triplets Found                       0.193566
True Model BIC                  -26121.895393
True Positives                       1.232031
dtype: float64

In [42]:
pd.concat(experiments_1.values()).groupby(level=0).agg(['mean', 'std'])

                                     True Positives           False Positives  \
                                               mean       std            mean
Chain (No Synergy)                              0.5  0.707107             1.5
Chain (With Synergy)                            2.0  1.414214             2.5
Chain with D                                    0.5  0.707107             3.0
Collider (Three Variables)                      1.5  0.707107             0.5
Collider with D                                 1.5  0.707107             0.5
Fork (Three Variables)                          0.0  0.000000             2.0
Fork Synergy (Three Variables)                  0.0  0.000000             2.0
Fork Synergy with D                             0.0  0.000000             3.5
Fork with D                                     0.0  0.000000             4.0
Large Discrete                                  0.5  0.707107             7.0
Mediator Synergy                                3.0  0.000000             1.0
Multi-Parent Synergy (4 Parents)                4.0  0.000000             4.5
Multi-Parent Synergy (5 Parents)                5.0  0.000000             7.0
Multi-Parent Synergy (Three Parents)            3.0  0.000000             1.5

                                               False Negatives            \
                                           std            mean       std
Chain (No Synergy)                    0.707107             1.5  0.707107
Chain (With Synergy)                  0.707107             1.0  1.414214
Chain with D                          1.414214             1.5  0.707107
Collider (Three Variables)            0.707107             1.5  0.707107
Collider with D                       0.707107             1.5  0.707107
Fork (Three Variables)                0.000000             2.0  0.000000
Fork Synergy (Three Variables)        0.000000             2.0  0.000000
Fork Synergy with D                   0.707107             2.0  0.000000
Fork with D                           0.000000             2.0  0.000000
Large Discrete                        4.242641             7.5  0.707107
Mediator Synergy                      0.000000             0.0  0.000000
Multi-Parent Synergy (4 Parents)      0.707107             0.0  0.000000
Multi-Parent Synergy (5 Parents)      0.000000             0.0  0.000000
Multi-Parent Synergy (Three Parents)  0.707107             0.0  0.000000

                                       SHD           Precision            \
                                      mean       std      mean       std
Chain (No Synergy)                     3.0  1.414214    0.2500  0.353553
Chain (With Synergy)                   3.5  2.121320    0.4250  0.247487
Chain with D                           4.5  0.707107    0.1000  0.141421
Collider (Three Variables)             2.0  1.414214    0.7500  0.353553
Collider with D                        2.0  0.000000    0.8335  0.235467
Fork (Three Variables)                 4.0  0.000000    0.0000  0.000000
Fork Synergy (Three Variables)         4.0  0.000000    0.0000  0.000000
Fork Synergy with D                    5.5  0.707107    0.0000  0.000000
Fork with D                            6.0  0.000000    0.0000  0.000000
Large Discrete                        14.5  3.535534    0.0455  0.064347
Mediator Synergy                       1.0  0.000000    0.7500  0.000000
Multi-Parent Synergy (4 Parents)       4.5  0.707107    0.4720  0.039598
Multi-Parent Synergy (5 Parents)       7.0  0.000000    0.4170  0.000000
Multi-Parent Synergy (Three Parents)   1.5  0.707107    0.6750  0.106066

                                      Recall           F1 Score
                                        mean       std     mean       std
Chain (No Synergy)                    0.2500  0.353553   0.2500  0.353553
Chain (With Synergy)                  0.6665  0.471640   0.5180  0.328098
Chain with D                          0.2500  0.353553   0.1430  0.202233
Collider (Three Variables)            0.5000  0.236174   0.6000  0.282843
Collider with D                       0.5000  0.236174   0.5835  0.118087
Fork (Three Variables)                0.0000  0.000000   0.0000  0.000000
Fork Synergy (Three Variables)        0.0000  0.000000   0.0000  0.000000
Fork Synergy with D                   0.0000  0.000000   0.0000  0.000000
Fork with D                           0.0000  0.000000   0.0000  0.000000
Large Discrete                        0.0625  0.088388   0.0525  0.074246
Mediator Synergy                      1.0000  0.000000   0.8570  0.000000
Multi-Parent Synergy (4 Parents)      1.0000  0.000000   0.6410  0.036770
Multi-Parent Synergy (5 Parents)      1.0000  0.000000   0.5880  0.000000
Multi-Parent Synergy (Three Parents)  1.0000  0.000000   0.8035  0.075660